version: '3'

services:
  # 开发容器
  dev:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: /bin/bash
  # Ubuntu 容器
  ubuntu:
    build:
      context: ./docker/ubuntu
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: /bin/bash
    environment:
      - DEBIAN_FRONTEND=noninteractive

  # Debian 容器
  debian:
    build:
      context: ./docker/debian
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: /bin/bash
    environment:
      - DEBIAN_FRONTEND=noninteractive

  # CentOS 容器
  centos:
    build:
      context: ./docker/centos
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: /bin/bash

  # Fedora 容器
  fedora:
    build:
      context: ./docker/fedora
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: /bin/bash

  # Alpine 容器
  alpine:
    build:
      context: ./docker/alpine
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: /bin/sh

  # ARM 架构模拟 (使用 QEMU)
  arm64:
    build:
      context: ./docker/arm64
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: /bin/bash
