version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - nashhd:/home/developer
    ports:
      - "8081:8080"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: unless-stopped

volumes:
  nashhd:
    external: true