<?php

/**
 * x86_64 (AMD64) 架构支持的PHP版本配置
 * 
 * 返回格式：[发行版][发行版版本][PHP版本] = 支持级别
 */
return [
    // Ubuntu
    'ubuntu' => [
        '22.04' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '20.04' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '18.04' => [
            '8.3' => 'partial',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'full',
            '7.1' => 'full',
        ],
    ],
    // Debian
    'debian' => [
        '12' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '11' => [
            '8.3' => 'partial',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '10' => [
            '8.3' => 'none',
            '8.2' => 'partial',
            '8.1' => 'partial',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'full',
            '7.1' => 'full',
        ],
    ],
    // CentOS/RHEL
    'centos' => [
        '9' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '8' => [
            '8.3' => 'partial',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '7' => [
            '8.3' => 'none',
            '8.2' => 'partial',
            '8.1' => 'partial',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'full',
            '7.1' => 'full',
        ],
    ],
    // RHEL
    'rhel' => [
        '9' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '8' => [
            '8.3' => 'partial',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '7' => [
            '8.3' => 'none',
            '8.2' => 'partial',
            '8.1' => 'partial',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'full',
            '7.1' => 'full',
        ],
    ],
    // Fedora
    'fedora' => [
        '38' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '37' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
        '36' => [
            '8.3' => 'partial',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
    ],
    // Alpine Linux
    'alpine' => [
        '3.18' => [
            '8.3' => 'full',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'none',
        ],
        '3.17' => [
            '8.3' => 'partial',
            '8.2' => 'full',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'partial',
            '7.2' => 'partial',
            '7.1' => 'none',
        ],
        '3.16' => [
            '8.3' => 'none',
            '8.2' => 'partial',
            '8.1' => 'full',
            '8.0' => 'full',
            '7.4' => 'full',
            '7.3' => 'full',
            '7.2' => 'partial',
            '7.1' => 'partial',
        ],
    ],
];
